// Import a Stoplight-style markdown KB (docs/en/<Category>/<Title>.md) into
// md-kb. Parses frontmatter (roles -> access_roles), maps category -> folder,
// rewrites ../../../images/X -> /kb-images/X, copies images into public/, and
// writes an idempotent SQL file of upserts.
//
// Usage:
//   node scripts/import-kb.mjs <source-repo-dir> [out.sql]
//
// Then load it:  psql "$DB_URL" -f <out.sql>

import { readdirSync, readFileSync, statSync, mkdirSync, copyFileSync, writeFileSync } from "node:fs";
import { join, basename, extname } from "node:path";

const SRC = process.argv[2];
const OUT = process.argv[3] ?? "/tmp/kb-import.sql";
if (!SRC) {
  console.error("usage: node scripts/import-kb.mjs <source-repo-dir> [out.sql]");
  process.exit(1);
}

const DOCS = join(SRC, "docs", "en");
const IMAGES_SRC = join(SRC, "images");
const IMAGES_DST = join(process.cwd(), "public", "kb-images");

function walk(dir) {
  const out = [];
  for (const name of readdirSync(dir)) {
    const p = join(dir, name);
    const st = statSync(p);
    if (st.isDirectory()) out.push(...walk(p));
    else if (extname(p) === ".md") out.push(p);
  }
  return out;
}

function slugify(s) {
  return s
    .toLowerCase().trim()
    .replace(/[^\w\s-]/g, "")
    .replace(/[\s_]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-|-$/g, "");
}

// Minimal frontmatter parser: returns { data, body }.
function parseFrontmatter(raw) {
  const m = /^---\s*\n([\s\S]*?)\n---\s*\n?/.exec(raw);
  if (!m) return { data: {}, body: raw };
  const data = {};
  for (const line of m[1].split("\n")) {
    const kv = /^([A-Za-z0-9_-]+)\s*:\s*(.*)$/.exec(line.trim());
    if (kv) data[kv[1]] = kv[2].replace(/^['"]|['"]$/g, "").trim();
  }
  return { data, body: raw.slice(m[0].length) };
}

// The articles come from the older SkyMind KB; align their role names to the
// current SkyCell `secure` realm group vocabulary (see intervention-client's
// `userRoles`). Adjust here if a name differs.
const ROLE_ALIASES = {
  CUSTOMER_ADMIN: "CUSTOMER_ADMIN_INTERVENTION",
  SITE_MANAGEMENT: "SITE_MANAGEMENT_INTERVENTION",
};

function parseRoles(value) {
  if (!value) return [];
  return value
    .split(",")
    .map((r) => r.trim())
    .filter(Boolean)
    .map((r) => ROLE_ALIASES[r] ?? r);
}

function rewriteImages(md) {
  // Rewrite any reference to the images/ folder -> /kb-images/, regardless of
  // prefix (./  ../  /  none), markdown angle-bracket URLs `](<...>)`, or
  // HTML <img src>. Filenames may contain spaces (kept inside < >).
  return md
    .replace(/(\]\(<?|src=["'])(?:\.{0,2}\/)*(?:assets\/)?images\//g, "$1/kb-images/");
}

const sqlEsc = (s) => `'${String(s).replace(/'/g, "''")}'`;
const sqlArr = (arr) =>
  `'{${arr.map((x) => `"${String(x).replace(/"/g, '\\"')}"`).join(",")}}'`;

const files = walk(DOCS);
const seen = new Set();
const rows = [];

for (const file of files) {
  const raw = readFileSync(file, "utf8");
  const { data, body } = parseFrontmatter(raw);
  const title = basename(file, ".md");
  const folder = file.slice(DOCS.length + 1, file.length - basename(file).length - 1); // category path

  let slug = slugify(title);
  while (seen.has(slug)) slug = `${slug}-${slugify(folder).slice(0, 6) || "x"}`;
  seen.add(slug);

  rows.push({
    slug,
    title,
    folder,
    access_roles: parseRoles(data.roles),
    content: rewriteImages(body).trim() + "\n",
  });
}

// Choose a dollar-quote tag not present in any content.
let TAG = "kbmd";
while (rows.some((r) => r.content.includes(`$${TAG}$`))) TAG += "x";
const dq = (s) => `$${TAG}$${s}$${TAG}$`;

const sql = [
  "-- Generated by scripts/import-kb.mjs — idempotent upserts.",
  "begin;",
  ...rows.map(
    (r) =>
      `insert into public.articles (slug,title,folder,content,access_roles,tags,published) values (` +
      `${sqlEsc(r.slug)},${sqlEsc(r.title)},${sqlEsc(r.folder)},${dq(r.content)},` +
      `${sqlArr(r.access_roles)},'{}',true) ` +
      `on conflict (slug) do update set title=excluded.title, folder=excluded.folder, ` +
      `content=excluded.content, access_roles=excluded.access_roles, published=true;`,
  ),
  "commit;",
  "",
].join("\n");

writeFileSync(OUT, sql);

// Copy images.
let copied = 0;
try {
  mkdirSync(IMAGES_DST, { recursive: true });
  for (const name of readdirSync(IMAGES_SRC)) {
    const sp = join(IMAGES_SRC, name);
    if (statSync(sp).isFile()) {
      copyFileSync(sp, join(IMAGES_DST, name));
      copied++;
    }
  }
} catch (e) {
  console.error("image copy warning:", e.message);
}

const roleHist = {};
for (const r of rows) for (const role of r.access_roles) roleHist[role] = (roleHist[role] ?? 0) + 1;

console.log(`Parsed ${rows.length} articles -> ${OUT}`);
console.log(`Copied ${copied} images -> public/kb-images/`);
console.log("Role distribution:", roleHist);
console.log("Public (no roles / BASIC_ACCESS):",
  rows.filter((r) => r.access_roles.length === 0 || r.access_roles.includes("BASIC_ACCESS")).length);
